name:           dummy-me
version:        '0.1.0.0'
category:       Web
author:         TAKAHASHI Yuto
maintainer:     ytaka23dev@gmail.com
copyright:      2017 TAKAHASHI Yuto
license:        BSD3
homepage:       https://github.com/y-taka-23/dummy-me#readme

extra-source-files:
- README.md

dependencies:
- base

library:
  source-dirs: src
  dependencies:
  - text
  - aeson
  - lens
  - lens-aeson
  - bytestring
  - vector
  - unordered-containers
  - scientific
  - Spock
  - optparse-applicative
  - http-types
  - wai-extra
  - unix
  - directory
  - filepath

executables:
  dummy-me:
    main: Main.hs
    source-dirs: app
    dependencies:
    - dummy-me

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - dummy-me
    - aeson
    - vector
    - lens
    - lens-aeson
    - unordered-containers
